// TYPES de los PROYECTOS.
export const MOSTRAR_FORMULARIO_PROYECTO = 'MOSTRAR_FORMULARIO_PROYECTO';
export const OCULTAR_FORMULARIO_PROYECTO = 'OCULTAR_FORMULARIO_PROYECTO';
export const EDITAR_PROYECTO = 'EDITAR_PROYECTO';
export const PROYECTO_ACTUALIZADO = 'PROYECTO_ACTUALIZADO'; 
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const MOSTRAR_MENSAJE = 'MOSTRAR_MENSAJE';
export const CREAR_PROYECTO = 'CREAR_PROYECTO';
export const PROYECTO_SELECCIONADO = 'PROYECTO_SELECCIONADO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

// TYPES de las TAREAS
export const OBTENER_TAREAS = 'OBTENER_TAREAS';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const MOSTRAR_MENSAJE_TAREA = 'MOSTRAR_MENSAJE_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const EDITAR_TAREA = 'EDITAR_TAREA';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';

// TYPES de los alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

// TYPES de la autenticación
export const REGISTRO_EXITO = 'REGISTRO_EXITO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITO = 'LOGIN_EXITO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
